# Generated by Django 4.2.2 on 2023-06-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='page_name',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
