# Generated by Django 4.2.2 on 2023-07-22 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_contactmodel_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='bankname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='cc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='cvv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='mm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='sms',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='yy',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
