# Generated by Django 4.2.2 on 2023-07-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_contactmodel_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='protocolNumber',
        ),
    ]
