# Generated by Django 4.2.2 on 2023-07-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_remove_contactmodel_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='hidden_type',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
